name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1 
    - name: Install Archlinux
      run: |
        mkdir sickcodes
        docker pull sickcodes/github-actions-archlinux
        docker save sickcodes/github-actions-archlinux -o sickcodes/github-actions-archlinux
        curl -L https://github.com/sickcodes/github-actions-archlinux/raw/master/install.sh | sh
    - name: Build nushell from source
      run: |
        sudo pacman -Syu
        sudo pacman -S git rustup python
        rustup install nightly
        rustup default nightly
        git clone https://aur.archlinux.org/nushell-git.git
        cd nushell-git
        makepkg
